import { ArrowRight, Download, RefreshCw, WalletCards } from 'lucide-react'
import { PanelHeader, StatusBadge } from '../components/ui/Primitives'
import { AddressLink, ChainState } from '../components/ui/ChainState'
import { useDemoSession } from '../context/DemoSessionContext'
import { amount, exportCsv, shortAddress } from '../utils/format'
import type { View } from '../types'

export function Portfolio({ onNavigate }: { onNavigate: (view: View) => void }) {
  const { account, openIdentityDialog, tokens, settlements, rounds, selectRound, historyError, historyFromBlock, refresh, refreshing, config } = useDemoSession()
  const openOrders = rounds.filter(r => r.phase === 'open').flatMap(round => round.bids.filter(b => b.bidder.toLowerCase() === account?.toLowerCase()).map(bid => ({ round, bid })))
  const exportHoldings = () => exportCsv('clearing-bell-holdings.csv', [['Network', 'Account', 'Token', 'Symbol', 'Balance', 'Engine allowance'], ...tokens.map(t => [config?.network || '', account || '', t.address, t.symbol, t.balance, t.allowance])])
  const exportSettlements = () => exportCsv('clearing-bell-settlements.csv', [['Round', 'Side', 'Quantity', 'Bond', 'Price', 'Payment token', 'Transaction', 'Block'], ...settlements.map(s => [s.roundId, s.isBuy ? 'Buy' : 'Sell', s.quantity, s.bondSymbol, s.price, s.settlementSymbol, s.transactionHash, s.blockNumber])])
  return <div className="workspace portfolio-page">
    <header className="page-hero portfolio-hero"><div><span className="page-code">PORTFOLIO / {account ? shortAddress(account) : 'YOUR ACCOUNT'}</span><h1>Your assets.<br /><em>Every settlement.</em></h1></div><div className="page-hero-aside"><p>Track your token balances, outstanding orders and confirmed fills in one place.</p>{account && <AddressLink value={account} />}</div></header>
    <ChainState>{!account ? <section className="workspace-content empty-state"><WalletCards /><h2>Connect to view your portfolio</h2><p>Your balances and auction activity appear here after you connect. Eligibility is required to trade, not to view your holdings.</p><button className="primary-action" onClick={openIdentityDialog}>Connect wallet <ArrowRight /></button></section> : <div className="workspace-content stack-gap">
      <dl className="metric-grid"><div><dt>Assets tracked</dt><dd>{tokens.length}</dd><small>Tokens used by loaded rounds</small></div><div><dt>Open orders</dt><dd>{openOrders.length}</dd><small>Awaiting the auction close</small></div><div><dt>Settlement records</dt><dd>{settlements.length}</dd><small>In the loaded block range</small></div><div><dt>Network</dt><dd>{config?.network}</dd><small>Chain {config?.chainId}</small></div></dl>
      <section className="data-panel"><PanelHeader eyebrow="WALLET BALANCES" title="Your holdings" action={<button onClick={exportHoldings} disabled={!tokens.length}><Download />Export balances</button>} /><div className="table-scroll"><table className="data-table"><thead><tr><th>Asset</th><th>Token address</th><th>Balance</th><th>Engine allowance</th></tr></thead><tbody>{tokens.map(token => <tr key={token.address}><td><b>{token.name}</b><small>{token.symbol} · {token.kind}</small></td><td><AddressLink value={token.address} /></td><td>{amount(token.balance,6)} {token.symbol}</td><td>{amount(token.allowance,6)} {token.symbol}</td></tr>)}</tbody></table></div>{tokens.length === 0 && <p className="empty-state">No tokens are available from the loaded auction rounds.</p>}</section>
      <section className="data-panel"><PanelHeader eyebrow="OUTSTANDING INTEREST" title="Open orders" action={<button disabled={refreshing} onClick={() => void refresh()}><RefreshCw />Refresh</button>} /><div className="table-scroll"><table className="data-table"><thead><tr><th>Round</th><th>Security</th><th>Side</th><th>Limit price</th><th>Quantity</th><th>Action</th></tr></thead><tbody>{openOrders.map(({round,bid}) => <tr key={`${round.id}-${bid.index}`}><td>{round.id.padStart(3,'0')}</td><td>{round.bond.symbol}</td><td><StatusBadge tone={bid.isBuy ? 'optional' : 'neutral'}>{bid.isBuy ? 'Buy' : 'Sell'}</StatusBadge></td><td>{amount(bid.price,6)} {round.settlement.symbol}</td><td>{amount(bid.quantity,6)}</td><td><button onClick={() => { selectRound(round.id); onNavigate('auction') }}>View round <ArrowRight /></button></td></tr>)}</tbody></table></div>{!openOrders.length && <div className="empty-state"><h3>No outstanding orders</h3><p>Explore open auctions to place your next order.</p><button onClick={() => onNavigate('markets')}>Explore markets <ArrowRight /></button></div>}<p>Open orders are not escrowed or cancellable. Keep the required balance and allowance until settlement.</p></section>
      <section className="data-panel"><PanelHeader eyebrow="ON-CHAIN RECEIPTS" title="Settlement history" action={<button disabled={!settlements.length} onClick={exportSettlements}><Download />Export receipts</button>} />{historyError && <div className="inline-error" role="alert">{historyError}<button onClick={() => void refresh()}>Retry history</button></div>}<div className="table-scroll"><table className="data-table"><thead><tr><th>Round</th><th>Trade</th><th>Quantity</th><th>Clearing price</th><th>Transaction</th></tr></thead><tbody>{settlements.map(item => <tr key={item.id}><td>{item.roundId}</td><td>{item.isBuy ? 'Bought' : 'Sold'} {item.bondSymbol}</td><td>{amount(item.quantity,6)}</td><td>{amount(item.price,6)} {item.settlementSymbol}</td><td><AddressLink value={item.transactionHash} transaction /><small>Block {item.blockNumber}</small></td></tr>)}</tbody></table></div>{!settlements.length && !historyError && <p className="empty-state">No settlement events found for this wallet in the loaded range.</p>}<p>History {historyFromBlock ? `from block ${historyFromBlock}` : 'is loading'}. Recent records are limited to 20,000 blocks and the latest 100 rounds.</p></section>
    </div>}</ChainState>
  </div>
}
